name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-* '
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-CPE-110-COT-1-1-pushswap-florentin.ganfon.git
  EXECUTABLES: 101pong

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url:
                ${{ env.MIRROR_URL }}
            ssh_private_key:
                ${{ secrets.GIT_SSH }}
